runtime: java
env: flex
runtime_config:
  runtime_version: 17
handlers:
  - url: /.*
    script: this field is required, but ignored


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7

resources:
  memory_gb: 2.0